Repository 4Subsea/fourinsight-api-python, pull requests merged in 2023-01, with the labels that each got.

#27 show correct inherited methods
  docs/_templates/autosummary/class.rst
  docs/api_ref/api.rst
  docs/api_ref/authentication.rst
  docs/api_ref/index.rst
Labels: chore

#29 Add user agent to request headers
  fourinsight/api/authenticate.py
  tests/test_authenticator.py
Labels: enhancement

#28 avoid creation of my_dir during tests
  tests/test_authenticator.py
Labels: test

#30 Remove print statement from authentication ("authentication from previous session is still valid")
  fourinsight/api/authenticate.py
Labels: enhancement

#32 Fix broken link + typo
  docs/user_guide/index.rst
Labels: chore

#31 Add support for handling paginated odata responses
  README.rst
  docs/index.rst
  docs/user_guide/api_calls.rst
  docs/user_guide/authentication.rst
  fourinsight/api/__init__.py
  fourinsight/api/authenticate.py
  tests/test_authenticator.py
Labels: enhancement
